### ISSUE TITLE
Most places do not check if the user is active. 

### ISSUE THREAD

**Issue by jstockwin** [jstockwin/Film-Night#19]
Should probably also only continue to send voting emails etc if the user has said they're attending film night.

**Comment by jstockwin** [comment]
Maybe this isn't an issue. Are inactive users banned users, or do they just not receive emails?

**Comment by jstockwin** [comment]
Bump @Tom-Johnston @unpairedbracket  - opinions?

**Comment by Tom-Johnston** [comment]
Inactive users used to just not get emails.

**Comment by unpairedbracket** [comment]
What does it actually mean for a user to be active?

**Comment by jstockwin** [comment]
@unpairedbracket  e.g. on the old system Chloe is an inactive user. In theory, they shouldn't be able to vote. The most important thing is probably that we are not spamming them with emails though.

**Comment by unpairedbracket** [comment]
Ah, right. Yeah, I'd agree with that.

**Comment by jstockwin** [comment]
Alright, closing this issue.
