### ISSUE TITLE
Push API support?

### ISSUE THREAD

**Issue by unpairedbracket** [jstockwin/Film-Night#21]
Support for the w3c [Push API](https://www.w3.org/TR/push-api/) could be cool for notifying us of roll-call/start of voting/results availability. Currently has basic support in Chrome 42 and more complete support in Firefox 44 https://developer.mozilla.org/en/docs/Web/API/Push_API

**Comment by unpairedbracket** [comment]
I've got the first bit of work done on this. It's in the webpush branch at bdf467ff4e331b29b3e63b264dea6f3c0091390d - if someone else wants to do any testing that'd be great. Currently works on FF and should work on Chrome when the manifest has our project ID and we get a GCM key. I've used a php var for the GCM API key that @Tom-Johnston'll need to get from Google so we can store it in an above-root php file like the db details if need be - should we be doing that with the client id as well, or is it fine as it is?

**Comment by Tom-Johnston** [comment]
I have an API key.

**Comment by jstockwin** [comment]
I would suggest making it a variable in database.php.

I'll add it to the one on the pis tomorrow.

**Comment by jstockwin** [comment]
@unpairedbracket API keys etc are now in database.php, and so provided this is included will be available to you on the pis. 

$push_api is the API key
$push_id is the project ID
$push_number is the project number. 

I'll also private message you with these so you can use them in your local dev environment.

**Comment by unpairedbracket** [comment]
I seem to still be having issues with registering to receive pushes in Chrome...
Maybe it's taking a while to enable GCM? I think the thing I saw had GCM for Chrome and GCM for Android APIs available, and we actually want the for android one - I probably should have mentioned that...

![selection_132](https://cloud.githubusercontent.com/assets/543022/12915584/2ec0bf30-cf24-11e5-88eb-add909af1abd.png)
^that one

**Comment by Tom-Johnston** [comment]
An Android API key is for sending the requests from an app. It requires a package name and the apps SHA-1 signing fingerprint. 

There are my options
![image](https://cloud.githubusercontent.com/assets/9396007/12915807/8502f420-cf25-11e5-8eca-2aaea237343b.png)

**Comment by unpairedbracket** [comment]
Oh, I guess they've updated that to make it less confusing.
Web server then, I guess...

**Comment by Tom-Johnston** [comment]
That's what you should have.

**Comment by Tom-Johnston** [comment]
We have a zero quota? 
![image](https://cloud.githubusercontent.com/assets/9396007/12916295/1b7e0810-cf29-11e5-96eb-e4ddc2cc824b.png)

**Comment by unpairedbracket** [comment]
I think I might have figured out the issue

**Comment by unpairedbracket** [comment]
Should the project-id be pluralised?

**Comment by Tom-Johnston** [comment]
No.

**Comment by unpairedbracket** [comment]
That's strange, because it works if it is, and not if it's not...

**Comment by unpairedbracket** [comment]
Now works on Chrome and Firefox.
