### ISSUE TITLE
Searching shouldn't return another instance of films already selected

### ISSUE THREAD

**Issue by unpairedbracket** [jstockwin/Film-Night#28]
![selection_096](https://cloud.githubusercontent.com/assets/543022/12754449/36707e8e-c9c3-11e5-83d4-d56ab7254682.png)

**Comment by Tom-Johnston** [comment]
Why not?

**Comment by unpairedbracket** [comment]
Because people might abuse it for films that aren't The Guard?

**Comment by Tom-Johnston** [comment]
They could just reload the page and add it again. Only allowing people to vote once should be handled server side. They could even send POST requests straight to the back end.

**Comment by jstockwin** [comment]
In theory this could be an issue, as people could give a certain film a really high frequency, making it very likely to come up. 

However, we currently completely ignore frequency, so doing this won't actually affect anything.

**Comment by jstockwin** [comment]
This is no longer a problem as you can no longer add multiple instances of a film which you have already nominated. If you select multiple films, each is handled in turn, so the first film will be "added", but after that nothing further will happen. 

The only slight problem is your veto preference for the last film in the list is the one that will stick, but that's your fault for trying to add a film more than once.
