### ISSUE TITLE
Check votes are valid.

### ISSUE THREAD

**Issue by Tom-Johnston** [jstockwin/Film-Night#43]
Votes of the wrong form can cause the JavaScript to get stuck in an infinite loop and crash. 
e.g.
- AV (and presumably the other runoff voting methods) loop forever if the only films to remove are not in the listOfCandidates.
- Borda count can't cope if a film isn't in a vote.

We should sanitise the votes either on the server, in the Javascript voting methods or both.

Fortunately the members are too nice and/or too incompetent to ruin film night by submitting votes of the wrong form. Unfortunately they have almost managed to ruin film night by submitting terrible films.

**Comment by Tom-Johnston** [comment]
Case in point. 
![image](https://cloud.githubusercontent.com/assets/9396007/12919267/3da8391c-cf3b-11e5-8a44-56d71122b8a8.png)

**Comment by jstockwin** [comment]
I have done this server side in 567bb2252c802b061adb2c315ba6504439d0c244

Assigning to @Tom-Johnston for JavaScript sanitation. If you don't feel this is necessary, then feel free to close this issue.
