### ISSUE TITLE
Favicon is the same colour as the theme

### ISSUE THREAD

**Issue by jstockwin** [jstockwin/Film-Night#48]
On android the favicon is not visible as it is the same colour as the theme. Can we use a white favicon if the user is on an android phone? Or should we just change the theme colour? 

![image](https://cloud.githubusercontent.com/assets/8227759/13053266/8430e662-d3fb-11e5-8308-c87a388aa3ab.png)

**Comment by Tom-Johnston** [comment]
We could use the accent color.

**Comment by jstockwin** [comment]
For the theme or the favicon?

**Comment by Tom-Johnston** [comment]
I was thinking for the favicon.

**Comment by jstockwin** [comment]
I agree that would be better on android, but might seem odd in full web browsers?

**Comment by jstockwin** [comment]
@Tom-Johnston this looks much better on android, but not so good on chrome:
![image](https://cloud.githubusercontent.com/assets/8227759/13084407/40e01866-d4d1-11e5-85c2-5294056db2f1.png)
Will leave this issue closed for now though, unless anyone has some better suggestions?

**Comment by unpairedbracket** [comment]
I've changed it to something that looks better on android than it did before, and like it did before on desktop. Let me know what you guys think

**Comment by Tom-Johnston** [comment]
I'm not currently seeing any favicon on my phone.

**Comment by jstockwin** [comment]
I am. The theme colour is darker than previous, and the favicon is the same colour. 

I like it. The theme colour being the same colour as the header looked a bit strange anyway.
