### ISSUE TITLE
Something is wrong with notifications

### ISSUE THREAD

**Issue by jstockwin** [jstockwin/Film-Night#65]
![image](https://cloud.githubusercontent.com/assets/8227759/13262675/e6653028-da5d-11e5-8ae6-bd9eebb24172.png)

**Comment by jstockwin** [comment]
Also, I received this at ~18:45. Notifications shouldn't be happening? 

However the one on my phone for voting start also had the same message, rather than a "voting has opened" message.

**Comment by jstockwin** [comment]
Have not had this since. It's probably been fixed in the huge re-write that went on during DB restructure.

**Comment by unpairedbracket** [comment]
Yeah, I think I probably successfully fixed it in d89922e or somewhere similar
